In [19]:
import numpy as np
from random import randint

### Initialise arrays

In [6]:
data = np.zeros((4,4))

In [270]:
data = np.random.randint(2, size=(10, 10))

In [271]:
data

array([[1, 1, 0, 1, 1, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 1, 0, 1, 1, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 1, 1, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 0, 1, 1, 0, 0]])

In [264]:
# Initialize with the same size of an existing array
data_zero = np.zeros_like(data)

In [265]:
data_zero

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### Examples of aggregations

##### https://jakevdp.github.io/PythonDataScienceHandbook/02.04-computation-on-arrays-aggregates.html

In [272]:
data.sum(axis=0)

array([6, 5, 4, 5, 5, 3, 7, 5, 3, 5])

In [273]:
data.sum(axis=1)

array([6, 6, 4, 6, 5, 1, 7, 2, 7, 4])

In [37]:
data[0]

array([1, 4, 2, 4, 1, 1, 3, 1, 2, 2])

### Slicing an array

In [42]:
# x[start:stop:step]
slice = data[0][::2]

In [43]:
slice

array([1, 2, 1, 3, 2])

In [44]:
# this slicing can also be done across all the axes
slice2 = data[::2]

In [45]:
slice2

array([[1, 4, 2, 4, 1, 1, 3, 1, 2, 2],
       [4, 2, 4, 2, 0, 2, 2, 2, 0, 0],
       [3, 0, 0, 4, 4, 0, 0, 4, 3, 0],
       [0, 1, 4, 4, 2, 2, 0, 2, 3, 3],
       [3, 0, 2, 1, 3, 2, 4, 4, 4, 1]])

In [46]:
# A potentially confusing case is when the step value is negative. 
# In this case, the defaults for start and stop are swapped. 
# This becomes a convenient way to reverse an array
single_row = data[0]
print(single_row)
reversed_row = single_row[::-1]
print(reversed_row)

[1 4 2 4 1 1 3 1 2 2]
[2 2 1 3 1 1 4 2 4 1]


### More slicing of multi-dim arrays

In [48]:
# This gived 3 rows and 5 columns
slice = data[:3,:5]
slice

array([[1, 4, 2, 4, 1],
       [1, 0, 1, 1, 4],
       [4, 2, 4, 2, 0]])

### Split an Array

In [14]:
data = np.random.randint(5, size=(10, 10))

In [254]:
def impose_components(img):
    print("image shape", img.shape)
    single_channel_length = int(img.shape[0]/3)
    print(single_channel_length)
    return np.array(np.vsplit(img, (296,592)))

In [255]:
data2 = np.random.randint(5, size=(887, 353))

In [262]:
rgb_img = impose_components(data2)
print(rgb_img.shape)
print(rgb_img[0].shape)
print(rgb_img[1].shape)
print(rgb_img[2].shape)

image shape (887, 353)
295
(3,)
(296, 353)
(296, 353)
(295, 353)


In [263]:
(296*2)+295

887

In [208]:
data

array([[2, 1, 3, 4, 3, 2, 4, 0, 2, 3],
       [0, 4, 2, 1, 3, 2, 3, 0, 2, 3],
       [2, 4, 2, 4, 3, 4, 3, 3, 2, 0],
       [1, 3, 4, 0, 4, 0, 0, 1, 1, 0],
       [2, 1, 2, 0, 4, 4, 3, 0, 4, 3],
       [1, 1, 0, 2, 0, 4, 1, 2, 3, 0],
       [0, 2, 0, 1, 3, 1, 1, 4, 1, 3],
       [3, 1, 0, 1, 0, 0, 4, 0, 4, 2],
       [2, 4, 1, 0, 0, 4, 2, 0, 0, 2],
       [0, 4, 0, 3, 3, 4, 0, 0, 4, 2]])

In [196]:
np.array(np.hsplit(data,2))

array([[[2, 1, 3, 4, 3],
        [0, 4, 2, 1, 3],
        [2, 4, 2, 4, 3],
        [1, 3, 4, 0, 4],
        [2, 1, 2, 0, 4],
        [1, 1, 0, 2, 0],
        [0, 2, 0, 1, 3],
        [3, 1, 0, 1, 0],
        [2, 4, 1, 0, 0],
        [0, 4, 0, 3, 3]],

       [[2, 4, 0, 2, 3],
        [2, 3, 0, 2, 3],
        [4, 3, 3, 2, 0],
        [0, 0, 1, 1, 0],
        [4, 3, 0, 4, 3],
        [4, 1, 2, 3, 0],
        [1, 1, 4, 1, 3],
        [0, 4, 0, 4, 2],
        [4, 2, 0, 0, 2],
        [4, 0, 0, 4, 2]]])

In [252]:
np.hsplit(data, (6,9))

[array([[2, 1, 3, 4, 3, 2],
        [0, 4, 2, 1, 3, 2],
        [2, 4, 2, 4, 3, 4],
        [1, 3, 4, 0, 4, 0],
        [2, 1, 2, 0, 4, 4],
        [1, 1, 0, 2, 0, 4],
        [0, 2, 0, 1, 3, 1],
        [3, 1, 0, 1, 0, 0],
        [2, 4, 1, 0, 0, 4],
        [0, 4, 0, 3, 3, 4]]), array([[4, 0, 2],
        [3, 0, 2],
        [3, 3, 2],
        [0, 1, 1],
        [3, 0, 4],
        [1, 2, 3],
        [1, 4, 1],
        [4, 0, 4],
        [2, 0, 0],
        [0, 0, 4]]), array([[3],
        [3],
        [0],
        [0],
        [3],
        [0],
        [3],
        [2],
        [2],
        [2]])]

In [198]:
# If the split is not possible, an error is raised
np.hsplit(data,3)

In [199]:
np.vsplit(data,2)

[array([[2, 1, 3, 4, 3, 2, 4, 0, 2, 3],
        [0, 4, 2, 1, 3, 2, 3, 0, 2, 3],
        [2, 4, 2, 4, 3, 4, 3, 3, 2, 0],
        [1, 3, 4, 0, 4, 0, 0, 1, 1, 0],
        [2, 1, 2, 0, 4, 4, 3, 0, 4, 3]]),
 array([[1, 1, 0, 2, 0, 4, 1, 2, 3, 0],
        [0, 2, 0, 1, 3, 1, 1, 4, 1, 3],
        [3, 1, 0, 1, 0, 0, 4, 0, 4, 2],
        [2, 4, 1, 0, 0, 4, 2, 0, 0, 2],
        [0, 4, 0, 3, 3, 4, 0, 0, 4, 2]])]

### Accessing array rows and columns

In [52]:
# Any row and columns can be accessed
slice = data[:3,:5]

In [53]:
slice

array([[1, 4, 2, 4, 1],
       [1, 0, 1, 1, 4],
       [4, 2, 4, 2, 0]])

In [56]:
# The first two columns
slice[:,0:2]

array([[1, 4],
       [1, 0],
       [4, 2]])

In [57]:
# The first two rows
slice[0:2,:]

array([[1, 4, 2, 4, 1],
       [1, 0, 1, 1, 4]])

### Finding the border execrcise

In [178]:
data = np.random.randint(100, size=(20))
threshold = 190

In [179]:
data

array([66, 91, 25,  3, 96, 78, 40, 49, 43, 51, 85, 39, 99, 41, 16, 82, 14,
        9, 41, 75])

In [180]:
data[1] = 200
data[2] = 2
data[3] = 194
data[16] = 195
data[19] = 199

In [181]:
data

array([ 66, 200,   2, 194,  96,  78,  40,  49,  43,  51,  85,  39,  99,
        41,  16,  82, 195,   9,  41, 199])

In [182]:
border_area = int(len(data)*.4)
print(border_area)
data[:border_area:]

8


array([ 66, 200,   2, 194,  96,  78,  40,  49])

In [183]:
def find_border_index(data, border_size = .4):
    border_region_size = int(len(data) * border_size)
    border_region = data[:border_region_size:]
    for index, number in np.ndenumerate(border_region):
        if data[index[0]] > threshold:
            if data[index[0]] > data[index[0]+1]:
                border_index = index[0]
    return border_index

In [190]:
def find_border_indexes_for_array(array):
    left_border = find_border_index(array)
    right_border = len(array) - find_border_index(array[::-1]) - 1
    
    return left_border, right_border

In [191]:
print(find_border_indexes_for_array(data))

(3, 16)


In [142]:
border_index = 0
for index, number in np.ndenumerate(data[:-1]):
    if data[index[0]] > threshold:
        if data[index[0]] > data[index[0]+1]:
            border_index = index[0]
print(border_index)
    

63
200
2
0
50
95
22
197
197
29
97
67
51
54
80
1
20
27
94
8


In [159]:
border_index = 0
reverse_array = data[::-1]
print(reverse_array)
for index, number in np.ndenumerate(reverse_array[:-1]):
    if reverse_array[index[0]] > threshold:
        if reverse_array[index[0]] > reverse_array[index[0]+1]:
            border_index = index[0]
print(border_index)

[ 57  94  27  20   1  80  54  51  67  97  29 197 197  22  95  50   0   2
 200  63]
18
